spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: manager
    url: jdbc:oracle:thin:@DESKTOP-UMHHVSE:1521/XE
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
